### ISSUE TITLE
requirements.txtの作成

### ISSUE THREAD

**Issue by Teoria-D** [MedakaVFX/pyside_examples#4]
# 変更の趣旨
`requirements.txt`を使って、「PySideをインストールした環境を作ってから開発を進めてほしい」という意図を明示的にしたいです

[requirements.txtについて](https://note.nkmk.me/python-pip-install-requirements/)

# 変更の理由
- 使う環境に`pip install -r requirements.txt`すれば、使える(テストできる)環境が得られるというのを周知すべきだと思ったから
- これに加えて、仮想環境(venv)周りを`README.md`もしくは`CONTRIBUTING.md`にまとめて共有したほうがいいかもしれないですね

[README.md, CONTRIBUTING.mdなどのGithub向けファイルについて](https://qiita.com/ukiuni@github/items/56ff7dd04c1c2748fbbb)

**Comment by YamagishiVFX** [comment]
提案、賛成です。

一方、ここはPySide6のExamplesのリポジトリなので、「開発環境」の話は別の所にまとめた方がいい気がしました。
一旦、Notionの方で仕様を固めた後、必要であれば書くリポジトリに対応させるのはどうでしょうか？？
もしくは、00_getting_startedの方でvenvなどの開発環境に触れるとか？

一旦、以下のページで提案をまとめてみるのはどうでしょうか？
[Notion | 開発 | 環境](https://www.notion.so/12c26830759c80fb911ec6a51a275ef6)

**Comment by Teoria-D** [comment]
承知しました、では時間ある時に
- `requirements.txtを追加してプルリクエスト`
- Notionの「環境」ページに、環境周りのページまとめ(実際どうやるかというより、前提知識をメインに)
という感じで進めてみますー
